networks:
  cheatsh_network:
    ipam:
      config:
        - subnet: ${CHEAT_NETWORK:-11.76.88.0/24}


services:
  cheatsh:
    build:
      context: ./app
    environment:
      CHEATSH_CACHE_TYPE: none
    networks:
      cheatsh_network:
        ipv4_address: ${CHEAT_IP:-11.76.88.254}
    restart: unless-stopped
    volumes:
      - ./app/upstream:/app/upstream:ro
      - ./sources/personal:/app/personal:ro
